package persistence;
// Generated 13 feb. 2018 10:14:40 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

	private String dni;
	private String nombreAlumno;
	private String apellidosAlumno;
	private Date fechaNacimiento;
	private Set matriculadoses = new HashSet(0);

	public Alumno() {
	}

	public Alumno(String dni) {
		this.dni = dni;
	}
	
	public Alumno(String dni, String nombreAlumno, String apellidosAlumno, Date fechaNacimiento) {
		this.dni = dni;
		this.nombreAlumno = nombreAlumno;
		this.apellidosAlumno = apellidosAlumno;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Alumno(String dni, String nombreAlumno, String apellidosAlumno, Date fechaNacimiento, Set matriculadoses) {
		this.dni = dni;
		this.nombreAlumno = nombreAlumno;
		this.apellidosAlumno = apellidosAlumno;
		this.fechaNacimiento = fechaNacimiento;
		this.matriculadoses = matriculadoses;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombreAlumno() {
		return this.nombreAlumno;
	}

	public void setNombreAlumno(String nombreAlumno) {
		this.nombreAlumno = nombreAlumno;
	}

	public String getApellidosAlumno() {
		return this.apellidosAlumno;
	}

	public void setApellidosAlumno(String apellidosAlumno) {
		this.apellidosAlumno = apellidosAlumno;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Set getMatriculadoses() {
		return this.matriculadoses;
	}

	public void setMatriculadoses(Set matriculadoses) {
		this.matriculadoses = matriculadoses;
	}

}
