package persistence;
// Generated 2 mar. 2018 10:38:08 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * MatriculadosId generated by hbm2java
 */
public class MatriculadosId implements java.io.Serializable {

	private String alumnov1Dni;
	private BigDecimal deportev1CodDeporte;

	public MatriculadosId() {
	}

	public MatriculadosId(String alumnov1Dni, BigDecimal deportev1CodDeporte) {
		this.alumnov1Dni = alumnov1Dni;
		this.deportev1CodDeporte = deportev1CodDeporte;
	}

	public String getAlumnov1Dni() {
		return this.alumnov1Dni;
	}

	public void setAlumnov1Dni(String alumnov1Dni) {
		this.alumnov1Dni = alumnov1Dni;
	}

	public BigDecimal getDeportev1CodDeporte() {
		return this.deportev1CodDeporte;
	}

	public void setDeportev1CodDeporte(BigDecimal deportev1CodDeporte) {
		this.deportev1CodDeporte = deportev1CodDeporte;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatriculadosId))
			return false;
		MatriculadosId castOther = (MatriculadosId) other;

		return ((this.getAlumnov1Dni() == castOther.getAlumnov1Dni()) || (this.getAlumnov1Dni() != null
				&& castOther.getAlumnov1Dni() != null && this.getAlumnov1Dni().equals(castOther.getAlumnov1Dni())))
				&& ((this.getDeportev1CodDeporte() == castOther.getDeportev1CodDeporte())
						|| (this.getDeportev1CodDeporte() != null && castOther.getDeportev1CodDeporte() != null
								&& this.getDeportev1CodDeporte().equals(castOther.getDeportev1CodDeporte())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAlumnov1Dni() == null ? 0 : this.getAlumnov1Dni().hashCode());
		result = 37 * result + (getDeportev1CodDeporte() == null ? 0 : this.getDeportev1CodDeporte().hashCode());
		return result;
	}

}
