package persistence;
// Generated 13 feb. 2018 10:14:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Monitor generated by hbm2java
 */
public class Monitor implements java.io.Serializable {

	private String dniMonitor;
	private String nombreMonitor;
	private String apellidosMonitor;
	private Set deportes = new HashSet(0);

	public Monitor() {
	}

	public Monitor(String dniMonitor) {
		this.dniMonitor = dniMonitor;
	}
	
	public Monitor(String dniMonitor, String nombreMonitor, String apellidosMonitor) {
		this.dniMonitor = dniMonitor;
		this.nombreMonitor = nombreMonitor;
		this.apellidosMonitor = apellidosMonitor;
	}


	public Monitor(String dniMonitor, String nombreMonitor, String apellidosMonitor, Set deportes) {
		this.dniMonitor = dniMonitor;
		this.nombreMonitor = nombreMonitor;
		this.apellidosMonitor = apellidosMonitor;
		this.deportes = deportes;
	}

	public String getDniMonitor() {
		return this.dniMonitor;
	}

	public void setDniMonitor(String dniMonitor) {
		this.dniMonitor = dniMonitor;
	}

	public String getNombreMonitor() {
		return this.nombreMonitor;
	}

	public void setNombreMonitor(String nombreMonitor) {
		this.nombreMonitor = nombreMonitor;
	}

	public String getApellidosMonitor() {
		return this.apellidosMonitor;
	}

	public void setApellidosMonitor(String apellidosMonitor) {
		this.apellidosMonitor = apellidosMonitor;
	}

	public Set getDeportes() {
		return this.deportes;
	}

	public void setDeportes(Set deportes) {
		this.deportes = deportes;
	}

}
