package persistence;
// Generated 13 feb. 2018 10:14:40 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Polideportivo generated by hbm2java
 */
public class Polideportivo implements java.io.Serializable {

	private BigDecimal codPolideportivo;
	private String nombrePolideportivo;
	private String direccionPolideportivo;
	private Set deportes = new HashSet(0);

	public Polideportivo() {
	}

	public Polideportivo(BigDecimal codPolideportivo) {
		this.codPolideportivo = codPolideportivo;
	}

	public Polideportivo(BigDecimal codPolideportivo, String nombrePolideportivo, String direccionPolideportivo,
			Set deportes) {
		this.codPolideportivo = codPolideportivo;
		this.nombrePolideportivo = nombrePolideportivo;
		this.direccionPolideportivo = direccionPolideportivo;
		this.deportes = deportes;
	}

	public BigDecimal getCodPolideportivo() {
		return this.codPolideportivo;
	}

	public void setCodPolideportivo(BigDecimal codPolideportivo) {
		this.codPolideportivo = codPolideportivo;
	}

	public String getNombrePolideportivo() {
		return this.nombrePolideportivo;
	}

	public void setNombrePolideportivo(String nombrePolideportivo) {
		this.nombrePolideportivo = nombrePolideportivo;
	}

	public String getDireccionPolideportivo() {
		return this.direccionPolideportivo;
	}

	public void setDireccionPolideportivo(String direccionPolideportivo) {
		this.direccionPolideportivo = direccionPolideportivo;
	}

	public Set getDeportes() {
		return this.deportes;
	}

	public void setDeportes(Set deportes) {
		this.deportes = deportes;
	}

}
