CREATE TABLE "ALUMNO" 
   (	"DNI" VARCHAR2(9 CHAR) NOT NULL ENABLE, 
	"NOMBRE_ALUMNO" VARCHAR2(50 CHAR), 
	"APELLIDOS_ALUMNO" VARCHAR2(100 CHAR), 
	"FECHA_NACIMIENTO" DATE, 
	 CONSTRAINT "ALUMNOV1_PK" PRIMARY KEY ("DNI")
   );