  CREATE TABLE "DEPORTE" 
   (	"COD_DEPORTE" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION_DEPORTE" VARCHAR2(150 CHAR), 
	"PRECIO_DEPORTE" NUMBER, 
	"POLIDEPORTIVOV1_COD_POLIDEPORTIVO" NUMBER NOT NULL ENABLE, 
	"MONITORV1_DNI_MONITOR" VARCHAR2(9 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "DEPORTEV1_PK" PRIMARY KEY ("COD_DEPORTE"),
	 CONSTRAINT "FK_DEPORTE_MONITOR" FOREIGN KEY ("MONITORV1_DNI_MONITOR")
	  REFERENCES "HR"."MONITOR" ("DNI_MONITOR") ENABLE, 
	 CONSTRAINT "FK_DEPORTE_POLIDEPORTIVO" FOREIGN KEY ("POLIDEPORTIVOV1_COD_POLIDEPORTIVO")
	  REFERENCES "HR"."POLIDEPORTIVO" ("COD_POLIDEPORTIVO") ENABLE
   );