CREATE TABLE "MONITOR" 
   (	"DNI_MONITOR" VARCHAR2(9 CHAR) NOT NULL ENABLE, 
	"NOMBRE_MONITOR" VARCHAR2(50 CHAR), 
	"APELLIDOS_MONITOR" VARCHAR2(100 CHAR), 
	 CONSTRAINT "MONITORV1_PK" PRIMARY KEY ("DNI_MONITOR")
   );