CREATE TABLE "POLIDEPORTIVO" 
   (	"COD_POLIDEPORTIVO" NUMBER NOT NULL ENABLE, 
	"NOMBRE_POLIDEPORTIVO" VARCHAR2(50 CHAR), 
	"DIRECCION_POLIDEPORTIVO" VARCHAR2(150 CHAR), 
	 CONSTRAINT "POLIDEPORTIVOV1_PK" PRIMARY KEY ("COD_POLIDEPORTIVO")
   );